### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by markusfalk** [sideroad/grunt-testem#10]
howdy, 

it would be nice if you could add a little more to the docs on what the plugin is used for. I just don't quite get the idea behind it. does ist start the testem server? does it open the testem server in browsers?

thanks alot.

**Comment by sideroad** [comment]
I've update README.md
As I mentioned on README.md, this grunt task use testem of ci mode. not used for dev mode.
If you want to any question or suggestion, plz let me know.
