### ISSUE TITLE
grunt watch and testem.json

### ISSUE THREAD

**Issue by svnlto** [sideroad/grunt-testem#5]
I'm calling a testem task from grunt watch and pretty often the task fails because the testem.json file your helper calls can't be generated in time.

**Comment by sideroad** [comment]
hmm..
Ill check it this weekends

**Comment by sideroad** [comment]
Ive try to watch task. but I did not reappearrevive occured as you said.
Please tell me your OS and grunt-testem version.
Could update grunt-testem version of your project?
