### ISSUE TITLE
travis-ci

### ISSUE THREAD

**Issue by svnlto** [sideroad/grunt-testem#7]
I've tried to run this as part of a travis-ci build but it keeps failing even tho it works fine locally.
unfortunately the errors aren't very helpful.

``` bash

Verifying property testem.main exists in config...OK
Now testing...
ERROR
>> 0/0 assertions failed
<WARN> Task "testem:main" failed. Use --force to continue. </WARN>

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

```

let me know if you need more info on this.

**Comment by sideroad** [comment]
hmm...
I assume travis-ci is not install testem.
testem presume to install globally environment.

**Comment by sideroad** [comment]
plz add below into .travis.xml
before_install: "npm -g install testem grunt"

**Comment by svnlto** [comment]
did that. but it seems to be hanging when executing phantomjs, so I doubt
it's related to this project at all.

**Comment by sideroad** [comment]
I've update grunt-testem for output testem tap into console.
use below
grunt --verbose testem

Good luck!
