### ISSUE TITLE
Leveraging existing testem.json and don't overwrite the file?

### ISSUE THREAD

**Issue by staxmanade** [sideroad/grunt-testem#9]
Hello,

Giving this package a quick go there were a couple assumptions that were different for me than I would expect.
1. The grunt task should leverage an existing testem.json file
2. The task should not overwrite an existing testem.json file.

I have spent time configuring my testem.json file would like to now use grunt to execute tests (for say a ci scenario).

Do you have any thoughts on my assumptions?

**Comment by sideroad** [comment]
Thanks for suggesting nice idea!
I've consider your suggestion.

I will implement additional specification below.
1. Be able to append json file into source file as testem.(please set existing testem.json path)
2. Task generate unique file name of testem json file such as grunt.testem.${unixtime}.json
3. Task remove above file after executed testem

2 and 3 specification are define for your requirement of remaining existing file

**Comment by staxmanade** [comment]
Thanks for considering it. Just to get clarification. I'm not sure I understand the need for 2&3 above if your tool just used the existing `testem.json` file already on disk?

thoughts?

**Comment by sideroad** [comment]
2&3 specifications are not for using existing `testem.json`. 
There are to take a step for not overwriting existing `testem.json`.

I've implement specifications today.
If you want to use existing testem.json, please set below example after install latest `grunt-testem`

``` js
grunt.initConfig({
  'testem': {
    main : {
      files : {
        'tests.tap': [ 'testem.json']
      }
    }
  }
});
```

Could you try it?
